name: medflow-tp2

services:

  patient-service:
    build:
      context: .
      dockerfile: patient-service/Dockerfile
    image: patient-image:1.0
    container_name: patient-service
    ports:
      - "8081:8081"
    networks:
      - medflow-net

  appointment-service:
    build:
      context: .
      dockerfile: appointment-service/Dockerfile
    image: appointment-image:1.0
    container_name: appointment-service
    environment:
      PATIENT_SERVICE_URL: http://patient-service:8081
    ports:
      - "8082:8082"
    depends_on:
      - patient-service
    networks:
      - medflow-net

networks:
  medflow-net:
    name: medflow-net
    driver: bridge
