### Listar pacientes
GET http://localhost:8081/patients

### Buscar paciente por id
GET http://localhost:8081/patients/1

### Paciente inexistente (404)
GET http://localhost:8081/patients/999

### Cadastrar paciente
POST http://localhost:8081/patients
Content-Type: application/json

{
  "cpf": "55566677788",
  "fullName": "Juliana Castro Mendes",
  "birthDate": "1990-05-14",
  "email": "juliana.mendes@email.com",
  "phone": "31988880005",
  "healthPlan": "Amil"
}

### Instancia que respondeu
GET http://localhost:8081/patients/info
