server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: patient-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
