server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: appointment-service

medflow:
  patient-service:
    url: ${PATIENT_SERVICE_URL:http://localhost:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
